# Generated by Django 4.0.5 on 2022-06-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=255)),
            ],
        ),
    ]
